feat(docker-build-images): handle single platform image simply

diff --git a/.github/workflows/__test-action-docker-build-image.yml b/.github/workflows/__test-action-docker-build-image.yml
--- a/.github/workflows/__test-action-docker-build-image.yml
+++ b/.github/workflows/__test-action-docker-build-image.yml
@@ -12,41 +12,75 @@ jobs:
       contents: read
       packages: write
     steps:
-      - uses: actions/checkout@v4
+      - name: Arrange - Checkout
+        uses: actions/checkout@v4
 
-      - run: |
+      - name: Arrange - Ensure token is set
+        run: |
           if [ -z "${{ github.token }}" ]; then
             echo "GitHub token is not set"
             exit 1
           fi
 
-      - id: build-image
+      - name: Act - Build image
+        id: build-image
         uses: ./actions/docker/build-image
         with:
           oci-registry: ghcr.io
           oci-registry-password: ${{ github.token }}
           context: "."
-          dockerfile: "./tests/application-1/Dockerfile"
+          dockerfile: "./tests/application/Dockerfile"
           target: "prod"
           platform: "linux/amd64"
-          image: ghcr.io/hoverkraft-tech/ci-github-container/application-1
-          labels: |
-            org.opencontainers.image.title=Application 1
-            org.opencontainers.image.description=Application 1
+          image: application-test
 
-      - name: Check build image ouput
+      - name: Assert - Check built image output
         uses: actions/github-script@v7.0.1
         with:
           script: |
             const assert = require("assert");
 
-            const imageOutput = `${{ steps.build-image.outputs.image }}`;
-            assert(imageOutput.length, `"image" output is empty`);
-            assert.equal(imageOutput,"ghcr.io/hoverkraft-tech/ci-github-container/application-1", `"image" output is not valid`);
+            const builtImageOutput = ${{ steps.build-image.outputs.built-image }};
+            assert(builtImageOutput, `"built-image" output is empty`);
+            assert.equal(builtImageOutput.name, "application-test", `"name" output is not valid`);
+            assert.equal(builtImageOutput.registry, "ghcr.io", `"registry" output is not valid`);
+            assert.equal(builtImageOutput.repository, "hoverkraft-tech/ci-github-container/application-test", `"repository" output is not valid`);
+            assert.equal(builtImageOutput.digests.length, 1, `"digests" output is not valid`);
+            assert.match(builtImageOutput.digests[0], /^ghcr\.io\/hoverkraft-tech\/ci-github-container\/application-test@sha256:[a-f0-9]{64}$/, `"digests" output is not valid`);
 
-            const digestOutput = `${{ steps.build-image.outputs.digest }}`;
-            assert(digestOutput.length, `"digest" output is empty`);
-            assert.match(digestOutput, /^sha256:[a-f0-9]{64}$/, `"digest" output is not a valid image digest`);
+            if (`${{ github.event_name }}` === "pull_request") {
+              const shortSha = `${{ github.sha }}`.substring(0, 7);
+              const prShaTag = `pr-${{ github.event.pull_request.number }}-${shortSha}`;
+              const prTag = `pr-${{ github.event.pull_request.number }}`;
+
+              assert.equal(builtImageOutput.tags.length, 2, `"tags" output is not valid`);
+              
+              assert.equal(builtImageOutput.tags[0], prShaTag, `"tags" output is not valid`);
+              assert.equal(builtImageOutput.tags[1], prTag, `"tags" output is not valid`);
+              
+              assert.equal(builtImageOutput.images.length, 2, `"images" output is not valid`);
+              assert.equal(builtImageOutput.images[0], `ghcr.io/hoverkraft-tech/ci-github-container/application-test:${prShaTag}`, `"images" output is not valid`);
+              assert.equal(builtImageOutput.images[1], `ghcr.io/hoverkraft-tech/ci-github-container/application-test:${prTag}`, `"images" output is not valid`);
+              
+            } else {
+              const refTag = `${{ github.ref }}`;
+
+              assert.equal(builtImageOutput.tags.length, 1, `"tags" output is not valid`);
+              assert.equal(builtImageOutput.tags, [refTag], `"tags" output is not valid`);
+
+              assert.equal(builtImageOutput.images.length, 1, `"images" output is not valid`);
+              assert.equal(builtImageOutput.images, [`ghcr.io/hoverkraft-tech/ci-github-container/application-test:${refTag}`], `"images" output is not valid`);
+            }
+
+            // Annotations
+            assert.match(builtImageOutput.annotations["org.opencontainers.image.created"], /[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z/, `"annotations.org.opencontainers.image.created" output is not valid`);
+            assert.equal(builtImageOutput.annotations["org.opencontainers.image.description"], "Opinionated GitHub actions and workflows for continuous integration in OCI context", `"annotations.org.opencontainers.image.authors" output is not valid`);
+            assert.equal(builtImageOutput.annotations["org.opencontainers.image.licenses"], "MIT", `"annotations.org.opencontainers.image.licenses" output is not valid`);
+            assert.match(builtImageOutput.annotations["org.opencontainers.image.revision"], /^[a-f0-9]{40}$/, `"annotations.org.opencontainers.image.revision" output is not valid`);
+            assert.equal(builtImageOutput.annotations["org.opencontainers.image.source"], "https://github.com/hoverkraft-tech/ci-github-container", `"annotations.org.opencontainers.image.source" output is not valid`);
+            assert.equal(builtImageOutput.annotations["org.opencontainers.image.title"], "ci-github-container", `"annotations.org.opencontainers.image.title" output is not valid`);
+            assert.equal(builtImageOutput.annotations["org.opencontainers.image.url"], "https://github.com/hoverkraft-tech/ci-github-container", `"annotations.org.opencontainers.image.url" output is not valid`);
+            assert.match(builtImageOutput.annotations["org.opencontainers.image.version"], /^pr-[0-9]+$/, `"annotations.org.opencontainers.image.version" output is not valid`);
 
       - uses: docker/login-action@v3
         with:
@@ -54,6 +88,17 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ github.token }}
 
-      - name: Check docker images
+      - name: Assert - Check docker digests
         run: |
-          docker manifest inspect "${{ steps.build-image.outputs.image }}@${{ steps.build-image.outputs.digest }}"
+          DIGESTS=$(echo '${{ steps.build-image.outputs.built-image }}' | jq -r '.digests[]')
+          for DIGEST in $DIGESTS; do
+            if ! docker pull "$DIGEST"; then
+              echo "Failed to pull $DIGEST"
+              exit 1
+            fi
+
+            if ! docker manifest inspect "$DIGEST"; then
+              echo "Failed to inspect $DIGEST"
+              exit 1
+            fi
+          done
diff --git a/.github/workflows/__test-workflow-docker-build-images.yml b/.github/workflows/__test-workflow-docker-build-images.yml
--- a/.github/workflows/__test-workflow-docker-build-images.yml
+++ b/.github/workflows/__test-workflow-docker-build-images.yml
@@ -22,17 +22,17 @@ jobs:
       images: |
         [
           {
-            "name": "application-1",
+            "name": "application-multi-arch",
             "context": ".",
-            "dockerfile": "./tests/application-1/Dockerfile",
+            "dockerfile": "./tests/application/Dockerfile",
             "build-args": { "PROD_MODE": "true" },
             "target": "prod",
             "platforms": ["linux/amd64","linux/arm64","linux/arm/v7"]
           },
           {
-            "name": "application-2",
+            "name": "application-mono-arch",
             "context": ".",
-            "dockerfile": "./tests/application-2/Dockerfile",
+            "dockerfile": "./tests/application/Dockerfile",
             "build-args": { "PROD_MODE": "true" },
             "target": "prod",
             "platforms": ["linux/amd64"]
@@ -63,23 +63,23 @@ jobs:
             assert(typeof builtImages === "object" && !Array.isArray(builtImages), `"built-images" output is not an object`);
             assert.equal(Object.keys(builtImages).length, 2, `"built-images" output does not contain 2 images`);
 
-            assert(builtImages["application-1"], `"built-images" output does not contain "application-1" image`);
+            assert(builtImages["application-multi-arch"], `"built-images" output does not contain "application-multi-arch" image`);
 
-            const application1Image = builtImages["application-1"];
-            assert.equal(application1Image.name, "application-1");
-            assert.equal(application1Image.registry, "ghcr.io");
-            assert.equal(application1Image.repository,"hoverkraft-tech/ci-github-container/application-1");
-            assert(application1Image.tags.length);
-            assert(application1Image.images.length);
-            application1Image.images.forEach(image => assert.match(image, /^ghcr\.io\/hoverkraft-tech\/ci-github-container\/application-1:[\.a-z0-9-]+$/));
+            const applicationMultiArchImage = builtImages["application-multi-arch"];
+            assert.equal(applicationMultiArchImage.name, "application-multi-arch");
+            assert.equal(applicationMultiArchImage.registry, "ghcr.io");
+            assert.equal(applicationMultiArchImage.repository,"hoverkraft-tech/ci-github-container/application-multi-arch");
+            assert(applicationMultiArchImage.tags.length);
+            assert(applicationMultiArchImage.images.length);
+            applicationMultiArchImage.images.forEach(image => assert.match(image, /^ghcr\.io\/hoverkraft-tech\/ci-github-container\/application-multi-arch:[\.a-z0-9-]+$/));
 
-            const application2Image = builtImages["application-2"];
-            assert.equal(application2Image.name, "application-2");
-            assert.equal(application2Image.registry, "ghcr.io");
-            assert.equal(application2Image.repository,"hoverkraft-tech/ci-github-container/application-2");
-            assert(application2Image.tags.length);
-            assert(application2Image.images.length);
-            application2Image.images.forEach(image => assert.match(image, /^ghcr\.io\/hoverkraft-tech\/ci-github-container\/application-2:[\.a-z0-9-]+$/));
+            const applicationMonoArchImage = builtImages["application-mono-arch"];
+            assert.equal(applicationMonoArchImage.name, "application-mono-arch");
+            assert.equal(applicationMonoArchImage.registry, "ghcr.io");
+            assert.equal(applicationMonoArchImage.repository,"hoverkraft-tech/ci-github-container/application-mono-arch");
+            assert(applicationMonoArchImage.tags.length);
+            assert(applicationMonoArchImage.images.length);
+            applicationMonoArchImage.images.forEach(image => assert.match(image, /^ghcr\.io\/hoverkraft-tech\/ci-github-container\/application-mono-arch:[\.a-z0-9-]+$/));
 
       - uses: docker/login-action@v3
         with:
@@ -89,7 +89,7 @@ jobs:
 
       - name: Check multi-arch docker image and manifest
         run: |
-          IMAGE="${{ fromJson(needs.act.outputs.built-images).application-1.images[0] }}"
+          IMAGE="${{ fromJson(needs.act.outputs.built-images).application-multi-arch.images[0] }}"
 
           docker pull "$IMAGE"
 
@@ -153,9 +153,9 @@ jobs:
           ANNOTATION_EXISTS=$(echo "${ANNOTATIONS}" | jq -e '.["org.opencontainers.image.url"] == "https://github.com/hoverkraft-tech/ci-github-container"')
           test "$ANNOTATION_EXISTS" = "true" || (echo "Expected annotation not found: org.opencontainers.image.url" && echo "$ANNOTATIONS" && exit 1)
 
-      - name: Check single-arch docker image
+      - name: Check mono-arch docker image
         run: |
-          IMAGE="${{ fromJson(needs.act.outputs.built-images).application-2.images[0] }}"
+          IMAGE="${{ fromJson(needs.act.outputs.built-images).application-mono-arch.images[0] }}"
 
           docker pull "$IMAGE"
 
@@ -166,7 +166,12 @@ jobs:
           fi
 
           # Check that there is only platforms
-          PLATFORMS=$(echo "${MANIFEST}" | jq -e '[.manifests[].platform]')
+          if ! PLATFORMS=$(echo "${MANIFEST}" | jq -e '[.manifests[].platform]'); then
+            echo "Failed to get platforms for image: ${IMAGE}"
+            echo "${MANIFEST}"
+            exit 1
+          fi
+
           NB_PLATFORMS=$(echo "${PLATFORMS}" | jq -e '. | length')
           if [ "$NB_PLATFORMS" != "1" ]; then
             echo "Expected 1 platform, got: $NB_PLATFORMS"
